/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ConsoleIndexRouteImport } from './routes/console.index'
import { Route as ConsoleDeploymentsRouteImport } from './routes/console.deployments'
import { Route as ConsoleIntegrationsRouteImport } from './routes/console.integrations'
import { Route as ConsoleLogsRouteImport } from './routes/console.logs'
import { Route as ConsoleNewRouteImport } from './routes/console.new'
import { Route as ConsoleTemplatesRouteImport } from './routes/console.templates'
import { Route as ConsoleProjectsIdRouteImport } from './routes/console.projects.$id'
import { Route as ConsoleSettingsActivityRouteImport } from './routes/console.settings.activity'
import { Route as ConsoleSettingsApiTokensRouteImport } from './routes/console.settings.api-tokens'
import { Route as ConsoleSettingsAppearanceRouteImport } from './routes/console.settings.appearance'
import { Route as ConsoleSettingsChannelsRouteImport } from './routes/console.settings.channels'
import { Route as ConsoleSettingsDangerRouteImport } from './routes/console.settings.danger'
import { Route as ConsoleSettingsNotificationsRouteImport } from './routes/console.settings.notifications'
import { Route as ConsoleSettingsProfileRouteImport } from './routes/console.settings.profile'
import { Route as ConsoleSettingsSecurityRouteImport } from './routes/console.settings.security'
import { Route as ConsoleProjectsIdIndexRouteImport } from './routes/console.projects.$id.index'
import { Route as ConsoleProjectsIdCanvasRouteImport } from './routes/console.projects.$id.canvas'
import { Route as ConsoleProjectsIdDatabaseRouteImport } from './routes/console.projects.$id.database'
import { Route as ConsoleProjectsIdDeploymentsRouteImport } from './routes/console.projects.$id.deployments'
import { Route as ConsoleProjectsIdLogsRouteImport } from './routes/console.projects.$id.logs'
import { Route as ConsoleProjectsIdOverviewRouteImport } from './routes/console.projects.$id.overview'
import { Route as ConsoleProjectsIdServiceLogsRouteImport } from './routes/console.projects.$id.service-logs'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleIndexRoute = ConsoleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleDeploymentsRoute = ConsoleDeploymentsRouteImport.update({
  id: '/deployments',
  path: '/deployments',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleIntegrationsRoute = ConsoleIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleLogsRoute = ConsoleLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleNewRoute = ConsoleNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleTemplatesRoute = ConsoleTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleProjectsIdRoute = ConsoleProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleSettingsActivityRoute = ConsoleSettingsActivityRouteImport.update({
  id: '/settings/activity',
  path: '/settings/activity',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleSettingsApiTokensRoute =
  ConsoleSettingsApiTokensRouteImport.update({
    id: '/settings/api-tokens',
    path: '/settings/api-tokens',
    getParentRoute: () => ConsoleRoute,
  } as any)
const ConsoleSettingsAppearanceRoute =
  ConsoleSettingsAppearanceRouteImport.update({
    id: '/settings/appearance',
    path: '/settings/appearance',
    getParentRoute: () => ConsoleRoute,
  } as any)
const ConsoleSettingsChannelsRoute = ConsoleSettingsChannelsRouteImport.update({
  id: '/settings/channels',
  path: '/settings/channels',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleSettingsDangerRoute = ConsoleSettingsDangerRouteImport.update({
  id: '/settings/danger',
  path: '/settings/danger',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleSettingsNotificationsRoute =
  ConsoleSettingsNotificationsRouteImport.update({
    id: '/settings/notifications',
    path: '/settings/notifications',
    getParentRoute: () => ConsoleRoute,
  } as any)
const ConsoleSettingsProfileRoute = ConsoleSettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleSettingsSecurityRoute = ConsoleSettingsSecurityRouteImport.update({
  id: '/settings/security',
  path: '/settings/security',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleProjectsIdIndexRoute = ConsoleProjectsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsoleProjectsIdRoute,
} as any)
const ConsoleProjectsIdCanvasRoute = ConsoleProjectsIdCanvasRouteImport.update({
  id: '/canvas',
  path: '/canvas',
  getParentRoute: () => ConsoleProjectsIdRoute,
} as any)
const ConsoleProjectsIdDatabaseRoute =
  ConsoleProjectsIdDatabaseRouteImport.update({
    id: '/database',
    path: '/database',
    getParentRoute: () => ConsoleProjectsIdRoute,
  } as any)
const ConsoleProjectsIdDeploymentsRoute =
  ConsoleProjectsIdDeploymentsRouteImport.update({
    id: '/deployments',
    path: '/deployments',
    getParentRoute: () => ConsoleProjectsIdRoute,
  } as any)
const ConsoleProjectsIdLogsRoute = ConsoleProjectsIdLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => ConsoleProjectsIdRoute,
} as any)
const ConsoleProjectsIdOverviewRoute =
  ConsoleProjectsIdOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => ConsoleProjectsIdRoute,
  } as any)
const ConsoleProjectsIdServiceLogsRoute =
  ConsoleProjectsIdServiceLogsRouteImport.update({
    id: '/service-logs',
    path: '/service-logs',
    getParentRoute: () => ConsoleProjectsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/console': typeof ConsoleRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/console/deployments': typeof ConsoleDeploymentsRoute
  '/console/integrations': typeof ConsoleIntegrationsRoute
  '/console/logs': typeof ConsoleLogsRoute
  '/console/new': typeof ConsoleNewRoute
  '/console/templates': typeof ConsoleTemplatesRoute
  '/console/': typeof ConsoleIndexRoute
  '/console/projects/$id': typeof ConsoleProjectsIdRouteWithChildren
  '/console/settings/activity': typeof ConsoleSettingsActivityRoute
  '/console/settings/api-tokens': typeof ConsoleSettingsApiTokensRoute
  '/console/settings/appearance': typeof ConsoleSettingsAppearanceRoute
  '/console/settings/channels': typeof ConsoleSettingsChannelsRoute
  '/console/settings/danger': typeof ConsoleSettingsDangerRoute
  '/console/settings/notifications': typeof ConsoleSettingsNotificationsRoute
  '/console/settings/profile': typeof ConsoleSettingsProfileRoute
  '/console/settings/security': typeof ConsoleSettingsSecurityRoute
  '/console/projects/$id/canvas': typeof ConsoleProjectsIdCanvasRoute
  '/console/projects/$id/database': typeof ConsoleProjectsIdDatabaseRoute
  '/console/projects/$id/deployments': typeof ConsoleProjectsIdDeploymentsRoute
  '/console/projects/$id/logs': typeof ConsoleProjectsIdLogsRoute
  '/console/projects/$id/overview': typeof ConsoleProjectsIdOverviewRoute
  '/console/projects/$id/service-logs': typeof ConsoleProjectsIdServiceLogsRoute
  '/console/projects/$id/': typeof ConsoleProjectsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/console/deployments': typeof ConsoleDeploymentsRoute
  '/console/integrations': typeof ConsoleIntegrationsRoute
  '/console/logs': typeof ConsoleLogsRoute
  '/console/new': typeof ConsoleNewRoute
  '/console/templates': typeof ConsoleTemplatesRoute
  '/console': typeof ConsoleIndexRoute
  '/console/settings/activity': typeof ConsoleSettingsActivityRoute
  '/console/settings/api-tokens': typeof ConsoleSettingsApiTokensRoute
  '/console/settings/appearance': typeof ConsoleSettingsAppearanceRoute
  '/console/settings/channels': typeof ConsoleSettingsChannelsRoute
  '/console/settings/danger': typeof ConsoleSettingsDangerRoute
  '/console/settings/notifications': typeof ConsoleSettingsNotificationsRoute
  '/console/settings/profile': typeof ConsoleSettingsProfileRoute
  '/console/settings/security': typeof ConsoleSettingsSecurityRoute
  '/console/projects/$id/canvas': typeof ConsoleProjectsIdCanvasRoute
  '/console/projects/$id/database': typeof ConsoleProjectsIdDatabaseRoute
  '/console/projects/$id/deployments': typeof ConsoleProjectsIdDeploymentsRoute
  '/console/projects/$id/logs': typeof ConsoleProjectsIdLogsRoute
  '/console/projects/$id/overview': typeof ConsoleProjectsIdOverviewRoute
  '/console/projects/$id/service-logs': typeof ConsoleProjectsIdServiceLogsRoute
  '/console/projects/$id': typeof ConsoleProjectsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/console': typeof ConsoleRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/console/deployments': typeof ConsoleDeploymentsRoute
  '/console/integrations': typeof ConsoleIntegrationsRoute
  '/console/logs': typeof ConsoleLogsRoute
  '/console/new': typeof ConsoleNewRoute
  '/console/templates': typeof ConsoleTemplatesRoute
  '/console/': typeof ConsoleIndexRoute
  '/console/projects/$id': typeof ConsoleProjectsIdRouteWithChildren
  '/console/settings/activity': typeof ConsoleSettingsActivityRoute
  '/console/settings/api-tokens': typeof ConsoleSettingsApiTokensRoute
  '/console/settings/appearance': typeof ConsoleSettingsAppearanceRoute
  '/console/settings/channels': typeof ConsoleSettingsChannelsRoute
  '/console/settings/danger': typeof ConsoleSettingsDangerRoute
  '/console/settings/notifications': typeof ConsoleSettingsNotificationsRoute
  '/console/settings/profile': typeof ConsoleSettingsProfileRoute
  '/console/settings/security': typeof ConsoleSettingsSecurityRoute
  '/console/projects/$id/canvas': typeof ConsoleProjectsIdCanvasRoute
  '/console/projects/$id/database': typeof ConsoleProjectsIdDatabaseRoute
  '/console/projects/$id/deployments': typeof ConsoleProjectsIdDeploymentsRoute
  '/console/projects/$id/logs': typeof ConsoleProjectsIdLogsRoute
  '/console/projects/$id/overview': typeof ConsoleProjectsIdOverviewRoute
  '/console/projects/$id/service-logs': typeof ConsoleProjectsIdServiceLogsRoute
  '/console/projects/$id/': typeof ConsoleProjectsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/console'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/auth/callback'
    | '/console/deployments'
    | '/console/integrations'
    | '/console/logs'
    | '/console/new'
    | '/console/templates'
    | '/console/'
    | '/console/projects/$id'
    | '/console/settings/activity'
    | '/console/settings/api-tokens'
    | '/console/settings/appearance'
    | '/console/settings/channels'
    | '/console/settings/danger'
    | '/console/settings/notifications'
    | '/console/settings/profile'
    | '/console/settings/security'
    | '/console/projects/$id/canvas'
    | '/console/projects/$id/database'
    | '/console/projects/$id/deployments'
    | '/console/projects/$id/logs'
    | '/console/projects/$id/overview'
    | '/console/projects/$id/service-logs'
    | '/console/projects/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/auth/callback'
    | '/console/deployments'
    | '/console/integrations'
    | '/console/logs'
    | '/console/new'
    | '/console/templates'
    | '/console'
    | '/console/settings/activity'
    | '/console/settings/api-tokens'
    | '/console/settings/appearance'
    | '/console/settings/channels'
    | '/console/settings/danger'
    | '/console/settings/notifications'
    | '/console/settings/profile'
    | '/console/settings/security'
    | '/console/projects/$id/canvas'
    | '/console/projects/$id/database'
    | '/console/projects/$id/deployments'
    | '/console/projects/$id/logs'
    | '/console/projects/$id/overview'
    | '/console/projects/$id/service-logs'
    | '/console/projects/$id'
  id:
    | '__root__'
    | '/'
    | '/console'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/auth/callback'
    | '/console/deployments'
    | '/console/integrations'
    | '/console/logs'
    | '/console/new'
    | '/console/templates'
    | '/console/'
    | '/console/projects/$id'
    | '/console/settings/activity'
    | '/console/settings/api-tokens'
    | '/console/settings/appearance'
    | '/console/settings/channels'
    | '/console/settings/danger'
    | '/console/settings/notifications'
    | '/console/settings/profile'
    | '/console/settings/security'
    | '/console/projects/$id/canvas'
    | '/console/projects/$id/database'
    | '/console/projects/$id/deployments'
    | '/console/projects/$id/logs'
    | '/console/projects/$id/overview'
    | '/console/projects/$id/service-logs'
    | '/console/projects/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsoleRoute: typeof ConsoleRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/': {
      id: '/console/'
      path: '/'
      fullPath: '/console/'
      preLoaderRoute: typeof ConsoleIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/deployments': {
      id: '/console/deployments'
      path: '/deployments'
      fullPath: '/console/deployments'
      preLoaderRoute: typeof ConsoleDeploymentsRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/integrations': {
      id: '/console/integrations'
      path: '/integrations'
      fullPath: '/console/integrations'
      preLoaderRoute: typeof ConsoleIntegrationsRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/logs': {
      id: '/console/logs'
      path: '/logs'
      fullPath: '/console/logs'
      preLoaderRoute: typeof ConsoleLogsRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/new': {
      id: '/console/new'
      path: '/new'
      fullPath: '/console/new'
      preLoaderRoute: typeof ConsoleNewRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/templates': {
      id: '/console/templates'
      path: '/templates'
      fullPath: '/console/templates'
      preLoaderRoute: typeof ConsoleTemplatesRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/projects/$id': {
      id: '/console/projects/$id'
      path: '/projects/$id'
      fullPath: '/console/projects/$id'
      preLoaderRoute: typeof ConsoleProjectsIdRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/settings/activity': {
      id: '/console/settings/activity'
      path: '/settings/activity'
      fullPath: '/console/settings/activity'
      preLoaderRoute: typeof ConsoleSettingsActivityRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/settings/api-tokens': {
      id: '/console/settings/api-tokens'
      path: '/settings/api-tokens'
      fullPath: '/console/settings/api-tokens'
      preLoaderRoute: typeof ConsoleSettingsApiTokensRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/settings/appearance': {
      id: '/console/settings/appearance'
      path: '/settings/appearance'
      fullPath: '/console/settings/appearance'
      preLoaderRoute: typeof ConsoleSettingsAppearanceRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/settings/channels': {
      id: '/console/settings/channels'
      path: '/settings/channels'
      fullPath: '/console/settings/channels'
      preLoaderRoute: typeof ConsoleSettingsChannelsRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/settings/danger': {
      id: '/console/settings/danger'
      path: '/settings/danger'
      fullPath: '/console/settings/danger'
      preLoaderRoute: typeof ConsoleSettingsDangerRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/settings/notifications': {
      id: '/console/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/console/settings/notifications'
      preLoaderRoute: typeof ConsoleSettingsNotificationsRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/settings/profile': {
      id: '/console/settings/profile'
      path: '/settings/profile'
      fullPath: '/console/settings/profile'
      preLoaderRoute: typeof ConsoleSettingsProfileRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/settings/security': {
      id: '/console/settings/security'
      path: '/settings/security'
      fullPath: '/console/settings/security'
      preLoaderRoute: typeof ConsoleSettingsSecurityRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/projects/$id/': {
      id: '/console/projects/$id/'
      path: '/'
      fullPath: '/console/projects/$id/'
      preLoaderRoute: typeof ConsoleProjectsIdIndexRouteImport
      parentRoute: typeof ConsoleProjectsIdRoute
    }
    '/console/projects/$id/canvas': {
      id: '/console/projects/$id/canvas'
      path: '/canvas'
      fullPath: '/console/projects/$id/canvas'
      preLoaderRoute: typeof ConsoleProjectsIdCanvasRouteImport
      parentRoute: typeof ConsoleProjectsIdRoute
    }
    '/console/projects/$id/database': {
      id: '/console/projects/$id/database'
      path: '/database'
      fullPath: '/console/projects/$id/database'
      preLoaderRoute: typeof ConsoleProjectsIdDatabaseRouteImport
      parentRoute: typeof ConsoleProjectsIdRoute
    }
    '/console/projects/$id/deployments': {
      id: '/console/projects/$id/deployments'
      path: '/deployments'
      fullPath: '/console/projects/$id/deployments'
      preLoaderRoute: typeof ConsoleProjectsIdDeploymentsRouteImport
      parentRoute: typeof ConsoleProjectsIdRoute
    }
    '/console/projects/$id/logs': {
      id: '/console/projects/$id/logs'
      path: '/logs'
      fullPath: '/console/projects/$id/logs'
      preLoaderRoute: typeof ConsoleProjectsIdLogsRouteImport
      parentRoute: typeof ConsoleProjectsIdRoute
    }
    '/console/projects/$id/overview': {
      id: '/console/projects/$id/overview'
      path: '/overview'
      fullPath: '/console/projects/$id/overview'
      preLoaderRoute: typeof ConsoleProjectsIdOverviewRouteImport
      parentRoute: typeof ConsoleProjectsIdRoute
    }
    '/console/projects/$id/service-logs': {
      id: '/console/projects/$id/service-logs'
      path: '/service-logs'
      fullPath: '/console/projects/$id/service-logs'
      preLoaderRoute: typeof ConsoleProjectsIdServiceLogsRouteImport
      parentRoute: typeof ConsoleProjectsIdRoute
    }
  }
}

interface ConsoleProjectsIdRouteChildren {
  ConsoleProjectsIdCanvasRoute: typeof ConsoleProjectsIdCanvasRoute
  ConsoleProjectsIdDatabaseRoute: typeof ConsoleProjectsIdDatabaseRoute
  ConsoleProjectsIdDeploymentsRoute: typeof ConsoleProjectsIdDeploymentsRoute
  ConsoleProjectsIdLogsRoute: typeof ConsoleProjectsIdLogsRoute
  ConsoleProjectsIdOverviewRoute: typeof ConsoleProjectsIdOverviewRoute
  ConsoleProjectsIdServiceLogsRoute: typeof ConsoleProjectsIdServiceLogsRoute
  ConsoleProjectsIdIndexRoute: typeof ConsoleProjectsIdIndexRoute
}

const ConsoleProjectsIdRouteChildren: ConsoleProjectsIdRouteChildren = {
  ConsoleProjectsIdCanvasRoute: ConsoleProjectsIdCanvasRoute,
  ConsoleProjectsIdDatabaseRoute: ConsoleProjectsIdDatabaseRoute,
  ConsoleProjectsIdDeploymentsRoute: ConsoleProjectsIdDeploymentsRoute,
  ConsoleProjectsIdLogsRoute: ConsoleProjectsIdLogsRoute,
  ConsoleProjectsIdOverviewRoute: ConsoleProjectsIdOverviewRoute,
  ConsoleProjectsIdServiceLogsRoute: ConsoleProjectsIdServiceLogsRoute,
  ConsoleProjectsIdIndexRoute: ConsoleProjectsIdIndexRoute,
}

const ConsoleProjectsIdRouteWithChildren =
  ConsoleProjectsIdRoute._addFileChildren(ConsoleProjectsIdRouteChildren)

interface ConsoleRouteChildren {
  ConsoleDeploymentsRoute: typeof ConsoleDeploymentsRoute
  ConsoleIntegrationsRoute: typeof ConsoleIntegrationsRoute
  ConsoleLogsRoute: typeof ConsoleLogsRoute
  ConsoleNewRoute: typeof ConsoleNewRoute
  ConsoleTemplatesRoute: typeof ConsoleTemplatesRoute
  ConsoleIndexRoute: typeof ConsoleIndexRoute
  ConsoleProjectsIdRoute: typeof ConsoleProjectsIdRouteWithChildren
  ConsoleSettingsActivityRoute: typeof ConsoleSettingsActivityRoute
  ConsoleSettingsApiTokensRoute: typeof ConsoleSettingsApiTokensRoute
  ConsoleSettingsAppearanceRoute: typeof ConsoleSettingsAppearanceRoute
  ConsoleSettingsChannelsRoute: typeof ConsoleSettingsChannelsRoute
  ConsoleSettingsDangerRoute: typeof ConsoleSettingsDangerRoute
  ConsoleSettingsNotificationsRoute: typeof ConsoleSettingsNotificationsRoute
  ConsoleSettingsProfileRoute: typeof ConsoleSettingsProfileRoute
  ConsoleSettingsSecurityRoute: typeof ConsoleSettingsSecurityRoute
}

const ConsoleRouteChildren: ConsoleRouteChildren = {
  ConsoleDeploymentsRoute: ConsoleDeploymentsRoute,
  ConsoleIntegrationsRoute: ConsoleIntegrationsRoute,
  ConsoleLogsRoute: ConsoleLogsRoute,
  ConsoleNewRoute: ConsoleNewRoute,
  ConsoleTemplatesRoute: ConsoleTemplatesRoute,
  ConsoleIndexRoute: ConsoleIndexRoute,
  ConsoleProjectsIdRoute: ConsoleProjectsIdRouteWithChildren,
  ConsoleSettingsActivityRoute: ConsoleSettingsActivityRoute,
  ConsoleSettingsApiTokensRoute: ConsoleSettingsApiTokensRoute,
  ConsoleSettingsAppearanceRoute: ConsoleSettingsAppearanceRoute,
  ConsoleSettingsChannelsRoute: ConsoleSettingsChannelsRoute,
  ConsoleSettingsDangerRoute: ConsoleSettingsDangerRoute,
  ConsoleSettingsNotificationsRoute: ConsoleSettingsNotificationsRoute,
  ConsoleSettingsProfileRoute: ConsoleSettingsProfileRoute,
  ConsoleSettingsSecurityRoute: ConsoleSettingsSecurityRoute,
}

const ConsoleRouteWithChildren =
  ConsoleRoute._addFileChildren(ConsoleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsoleRoute: ConsoleRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
